In [2]:
# CREATE A 3 CROSS 3 ARRAY OF ALL TRUE
import numpy as np
array = np.ones((3,3),dtype = bool)
print("New_array:",array)

New_array: [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [4]:
# CREATE A 1D ARRAY OF 10 EVENLY SPACED VALUES BETWEEN 5 AND 50 
import numpy as np
array = np.linspace(5,50,10)
print("new_array:",array)

new_array: [ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [6]:
# CONVERT A PYTHON LIST INTO ARRAY.
import numpy as np
list = [10,20,30,40,50]
print("List:",list)
array = np.array(list)
print("New_array:",array)

List: [10, 20, 30, 40, 50]
New_array: [10 20 30 40 50]


In [7]:
# REVERSE A 1D NUMPY ARRAY
import  numpy as np
array = np.array([10,20,30,40,50])
print("Array:",array)
reversed_array = array[ : :-1]
print("New_array:",reversed_array)

Array: [10 20 30 40 50]
New_array: [50 40 30 20 10]


In [8]:
# CREATE 3 CROSS 3 IDENTITY MATRIX
import numpy as np
array = np.eye(3)
print("Matrix:",array)

Matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
# CREATE 4 CROSS 4 ARRAY AND COMPUTE FIRST ROW AND last  COLUMN
import numpy as np 
array = np.arange(1,17).reshape(4,4)
print("Array:",array)
first_row = array[0, :]
print("First_row:",first_row)
last_column = array[:, -1]
print("Last_column:",last_column)

Array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
First_row: [1 2 3 4]
Last_column: [ 4  8 12 16]


In [22]:
#  CREATE 4 CROSS 4 ARRAY AND COMPUTE FIRST TWO ROW AND LAST TWO COLUMN 
import numpy as np 
arr = np.arange(1,17).reshape(4,4)
print("Array:",arr)
first_row = arr[:2, :2]
print("First_row:", first_row)
first_column = arr[:2, :2]
print("First_column:",first_column)

Array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
First_row: [[1 2]
 [5 6]]
First_column: [[1 2]
 [5 6]]


In [23]:
# PERFORM ARITHEMATIC OPERATIONS 
import numpy as np
a =  np.array([10,20,30])
b = np.array([18,24,32])
print("Array_A:",a)
print("Array_B:",b)
print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)

Array_A: [10 20 30]
Array_B: [18 24 32]
Addition: [28 44 62]
Subtraction: [-8 -4 -2]
Multiplication: [180 480 960]
Division: [0.55555556 0.83333333 0.9375    ]


In [24]:
#  TO CALCULATE THE DOT PRODUCT OF TWO ARRAY
import numpy as np
a = np.array([10,20,30])
b = np.array([40,50,60])
print("Array_A:",a)
print("Array_B:",b)
c = np.dot(a,b)
print("Dot product:",c)

Array_A: [10 20 30]
Array_B: [40 50 60]
Dot product: 3200


In [31]:
# COMPUTE MEAN ,MEDIAN AND STANDARD DEVIATION OF NUMPY ARRAY
import numpy as np
a = np.array([10,20,30,40,50])
print("Array_A:",a)
mean = np.mean(a)
median = np.median(a)
std = np.std(a)
print("Mean:",mean)
print("Median:",median)
print("Std:",std)

Array_A: [10 20 30 40 50]
Mean: 30.0
Median: 30.0
Std: 14.142135623730951
